### PR TITLE
pass compendium flag

### PR DESCRIPTION
**Pull request by bb46003**
pass compendium flag to items added from charaktersheet, this will allow to refresh item from compendium for translation module or from system it self if we add this function

### CODE REVIEW

**Comment by Muttley** [comment]
This would only add the flags if you add an item through the selectors, I'm assuming they're added by Babele itself elsewhere (for example, when you drop an item on the sheet from a compendium)?

**Comment by Muttley** [comment]
Can you provide your Babele config?  I would like to test this locally.

**Comment by bb46003** [comment]
Here is my module https://foundryvtt.com/packages/fallout-pl

**Comment by Muttley** [comment]
> Here is my module https://foundryvtt.com/packages/fallout-pl

Thank you.

**Comment by Muttley** [comment]
This flag doesn't appear to be used by Babele, it looks like it uses the `_stats.compendiumSource` field which we are not setting.

I'll amend the Item Selector to populate this field when adding items to an Actor, which should resolve your actual issue so new/custom flags are not required.

I've opened #454 for this request.

**Pull request closed without merging**
