### PR TITLE
weapon skill translation

### PR DESCRIPTION
**Pull request by bb46003**
insted of fix weaponskill use localize, fix problem when  translation module translate skill pack,

as you ask I push only file wich are related to function, sorry for pproblems it is my first bigger project I'm still larning

### CODE REVIEW

**Comment by Muttley** [comment]
> as you ask I push only file wich are related to function, sorry for pproblems it is my first bigger project I'm still larning

No problem.  Is there a related Issue for this?

**Comment by bb46003** [comment]
i think, there is no ticket for this,  i just recognie this, when i translate skill pack there are problems with weapons rolls

**Comment by Muttley** [comment]
@bb46003 How would you like to be credited in the release notes for this fix?

**Comment by bb46003** [comment]
Just Bartek

**Comment by Muttley** [comment]
> Just Bartek

Done

**Pull request merged**
